### ISSUE TITLE
modmod: Support images in exercise descriptions

### ISSUE THREAD

**Issue by g-braeunlich** [trifectatechfoundation/teach-rs#118]
What do you think about adding support for images / other static files in exercise descriptions?
Or is this already supported somehow?

Usecase: I am working on an exercise for wasm and I would like to show an image of the result in the exercise description (of course, it also would be cool to embed some wasm animation).

**Comment by hdoordt** [comment]
Hey @g-braeunlich I think this would be a great idea! You can probably take inspiration from the way images get included in the slides.
