### ISSUE TITLE
Website / book links are broken

### ISSUE THREAD

**Issue by iamoeg** [trifectatechfoundation/teach-rs#125]
The index page is actually fine, but you cannot access the book section for any of the tracks (screenshot bellow, same result on Firefox, Chromium and Vivaldi). Download links for the exercises work fine though. Anyway, interesting project, I see how it could be a great resource for anyone looking to learn or teach Rust, so thanks for the work! 😊

![Screenshot_20240723_114327](https://github.com/user-attachments/assets/4a8aecf9-99e4-406b-8ca3-6a63c69b2cbc)

**Comment by hdoordt** [comment]
@marlonbaeten can you have a look?

**Comment by marlonbaeten** [comment]
Fixed. Paths without a trailing slash were not resolved to a index.html file. I have added a redirect that fixes this.
